runtime: java25
entrypoint: 'java -cp "*" com.dencode.web.server.ServerMain'

inbound_services:
- warmup

handlers:
- url: .*
  script: dummy
  secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 5
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: 5000ms
