runtime: java11
entrypoint: 'java -cp "*" com.dencode.web.server.ServerMain'
inbound_services:
- warmup
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 2000ms
  max_pending_latency: automatic
